### ISSUE TITLE
Issues Handling

### ISSUE THREAD

**Issue by candcconsulting** [Cerenzengin/IssueMap2dMarkers#1]
Hi Ceren,
Currently the points are being loaded through a points generator ...
export class RandomPointGenerator extends BasePointGenerator {
  private _rng: BasicPRNG;

  constructor() {
    super();
    this._rng = new BasicPRNG(Math.random() * 10000);
  }

However, as these are loaded into a document handler (such as MongoDB) then we need to attach description etc and therefore that process will need ripping out.

If you consider the iTwin Accreditation how they build the html marker with the data pulled that would be a better method.

Therefore I propose that you refactor this code with the accreditation marker code.

I will create a getData function that returns the data from mongoDB

**Comment by candcconsulting** [comment]
This has been implemented
![image](https://github.com/Cerenzengin/IssueMap2dMarkers/assets/19268085/a613570c-ee93-41a6-9fe6-6a5c9c64bc05)
mongo.ts has the getAllIssues function
In Realm a new function was added
getAllIssues
exports = function(){

  let collection = context.services.get("mongodb-atlas").db("EnteredIssues").collection("itwin");
  
  return collection.find()
};
and anonymous users were allowed get getAllData
https://realm.mongodb.com/groups/659801d080e05362671ae4e9/apps/659a9e63fa4e38037ce2160b/auth/providers
https://realm.mongodb.com/groups/659801d080e05362671ae4e9/apps/659a9e63fa4e38037ce2160b/rules/mongodb-atlas/rule/659c0eefd4e21831de7f3ec8
If you open the console and press Load Issues the data will be available

**Comment by Cerenzengin** [comment]
https://stackoverflow.com/questions/51124721/calling-mongoose-from-react-client-side

Apparently,I couldn't use mongoose on client side so I write a backend with nodejs (with one of my friend) and make them talk via rest API. 

 React --> Nodejs--> MongoDB ( I can send data like that)

What do you think, should I continue with my backend application for mongodb access or should I try for realm integration?

**Comment by candcconsulting** [comment]
Realm is extremely easy … it builds your backend …

 

I found it very easy …

 

You can see with nearly one call I am getting all issues data … writing is the same, but you need to put some authentication around it

**Comment by candcconsulting** [comment]
Oh I see I had to fork to push my changes

https://github.com/candcconsulting/IssueMap2dMarkers/tree/master/src

 

if you add me as a contributor I can push the files I changed

**Comment by Cerenzengin** [comment]
I will analyse both of them then continue with one of them, really thanks a lot.


For adding the contributor, I think I already add you as collaborator but is it something else ? How can I do it? As I see in github you made the fork but should I make something else for you ?

________________________________
Gönderen: C&C Consulting ***@***.***>
Gönderildi: 8 Ocak 2024 Pazartesi 19:06:28
Kime: Cerenzengin/IssueMap2dMarkers
Bilgi: Zengin, Ceren; Comment
Konu: Re: [Cerenzengin/IssueMap2dMarkers] Issues Handling (Issue #1)


Oh I see I had to fork to push my changes

https://github.com/candcconsulting/IssueMap2dMarkers/tree/master/src



if you add me as a contributor I can push the files I changed

**Comment by candcconsulting** [comment]
Did you add ***@***.*** ***@***.***>  or the ***@***.*** ***@***.***>  ?

**Comment by glenworrall** [comment]
You should be able to see my fork ... for some reason it has pushed the lock files ... need to exclude them ... but if you look at the forks ...

The changes are straightforward ... I made most of the changes in Atlas
[cid:0e94d7e9-7468-44df-8735-473d96b3773c]

Glen Worrall

________________________________
